-- 20260426_audit_log.sql
-- Enable audit logging for all mutating operations via Edge Functions

create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  event_type text not null,
  actor_member_id uuid not null references members(id) on delete cascade,
  resource_table text not null,
  resource_id uuid not null,
  before jsonb,
  after jsonb,
  metadata jsonb default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

comment on table audit_log is 'Central audit log for all mutating operations routed through Edge Functions.';
comment on column audit_log.event_type is 'Type of mutation: expense.create, expense.update, expense.delete, settlement.create, contribution.create, profile.name_update';
comment on column audit_log.actor_member_id is 'Member performing the action (from JWT sub claim)';
comment on column audit_log.resource_table is 'Table modified: expenses, settlements, contributions, members';
comment on column audit_log.resource_id is 'Primary key of the affected row';

-- Indexes for query patterns
create index idx_audit_log_actor on audit_log(actor_member_id, created_at desc);
create index idx_audit_log_resource on audit_log(resource_table, resource_id, created_at desc);
create index idx_audit_log_event on audit_log(event_type, created_at desc);

-- Row Level Security: members can read audit entries for their groups only
alter table audit_log enable row level security;

create policy "Members can read audit log for their groups" on audit_log
  for select
  using (
    exists (
      select 1 from group_members gm
      where gm.member_id = actor_member_id
    )
  );

-- Insert policy: only service role (Edge Functions) can write
create policy "Service role only" on audit_log
  for insert
  with check (false);

-- Create helper function to emit audit log (callable from EF TS code)
create or replace function log_audit(
  p_event_type text,
  p_actor_member_id uuid,
  p_resource_table text,
  p_resource_id uuid,
  p_before jsonb default null,
  p_after jsonb default null,
  p_metadata jsonb default '{}'
) returns void
language plpgsql
security definer
as $$
begin
  insert into audit_log (
    event_type, actor_member_id, resource_table, resource_id, before, after, metadata
  ) values (
    p_event_type, p_actor_member_id, p_resource_table, p_resource_id, p_before, p_after, p_metadata
  );
end;
$$;

grant execute on function log_audit to service_role;
